
# This file is automatically generated, you probably don't want to edit this

boxplotmethodOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "boxplotmethodOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            useIQR = TRUE,
            iqrLimitMild = 1.5,
            iqrLimitExtreme = 3,
            box = FALSE, ...) {

            super$initialize(
                package="outlierz",
                name="boxplotmethod",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group)
            private$..useIQR <- jmvcore::OptionBool$new(
                "useIQR",
                useIQR,
                default=TRUE)
            private$..iqrLimitMild <- jmvcore::OptionNumber$new(
                "iqrLimitMild",
                iqrLimitMild,
                default=1.5)
            private$..iqrLimitExtreme <- jmvcore::OptionNumber$new(
                "iqrLimitExtreme",
                iqrLimitExtreme,
                default=3)
            private$..box <- jmvcore::OptionBool$new(
                "box",
                box,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..useIQR)
            self$.addOption(private$..iqrLimitMild)
            self$.addOption(private$..iqrLimitExtreme)
            self$.addOption(private$..box)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        useIQR = function() private$..useIQR$value,
        iqrLimitMild = function() private$..iqrLimitMild$value,
        iqrLimitExtreme = function() private$..iqrLimitExtreme$value,
        box = function() private$..box$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..useIQR = NA,
        ..iqrLimitMild = NA,
        ..iqrLimitExtreme = NA,
        ..box = NA)
)

boxplotmethodResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "boxplotmethodResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Outliers via boxplot method")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Outliers boxplot"))}))

boxplotmethodBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "boxplotmethodBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "outlierz",
                name = "boxplotmethod",
                version = c(1,0,0),
                options = options,
                results = boxplotmethodResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Boxplots
#'
#' 
#' @param data .
#' @param dep .
#' @param group .
#' @param useIQR \code{TRUE} or \code{FALSE} (default), use z-scores for
#'   outlier detection
#' @param iqrLimitMild a number specifying iqr distance for mild outliers
#' @param iqrLimitExtreme a number specifying iqr distance for extreme
#'   outliers
#' @param box \code{TRUE} or \code{FALSE} (default), provide box plots
#'   (continuous variables only)
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
boxplotmethod <- function(
    data,
    dep,
    group,
    useIQR = TRUE,
    iqrLimitMild = 1.5,
    iqrLimitExtreme = 3,
    box = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("boxplotmethod requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL))


    options <- boxplotmethodOptions$new(
        dep = dep,
        group = group,
        useIQR = useIQR,
        iqrLimitMild = iqrLimitMild,
        iqrLimitExtreme = iqrLimitExtreme,
        box = box)

    analysis <- boxplotmethodClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

