
# This file is automatically generated, you probably don't want to edit this

boxplotmethodOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "boxplotmethodOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            iqrLimitMild = 1.5,
            iqrLimitExtreme = 3,
            box = FALSE, ...) {

            super$initialize(
                package="outlierz",
                name="boxplotmethod",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..iqrLimitMild <- jmvcore::OptionNumber$new(
                "iqrLimitMild",
                iqrLimitMild,
                default=1.5)
            private$..iqrLimitExtreme <- jmvcore::OptionNumber$new(
                "iqrLimitExtreme",
                iqrLimitExtreme,
                default=3)
            private$..box <- jmvcore::OptionBool$new(
                "box",
                box,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..iqrLimitMild)
            self$.addOption(private$..iqrLimitExtreme)
            self$.addOption(private$..box)
        }),
    active = list(
        dep = function() private$..dep$value,
        iqrLimitMild = function() private$..iqrLimitMild$value,
        iqrLimitExtreme = function() private$..iqrLimitExtreme$value,
        box = function() private$..box$value),
    private = list(
        ..dep = NA,
        ..iqrLimitMild = NA,
        ..iqrLimitExtreme = NA,
        ..box = NA)
)

boxplotmethodResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "boxplotmethodResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        summary = function() private$.items[["summary"]],
        iqrscores = function() private$.items[["iqrscores"]],
        boxplot = function() private$.items[["boxplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Outliers via boxplot method")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Outliers boxplot"))
            self$add(jmvcore::Table$new(
                options=options,
                name="summary",
                title="Summary of results",
                visible=TRUE,
                rows=1,
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="missing", 
                        `title`="missing", 
                        `type`="integer"),
                    list(
                        `name`="outliers_low_extreme", 
                        `superTitle`="outliers", 
                        `title`="low extreme", 
                        `type`="integer"),
                    list(
                        `name`="outliers_low_mild", 
                        `superTitle`="outliers", 
                        `title`="low mild", 
                        `type`="integer"),
                    list(
                        `name`="outliers_high_mild", 
                        `superTitle`="outliers", 
                        `title`="high mild", 
                        `type`="integer"),
                    list(
                        `name`="outliers_high_extreme", 
                        `superTitle`="outliers", 
                        `title`="high extreme", 
                        `type`="integer"),
                    list(
                        `name`="outliers_total", 
                        `superTitle`="outliers", 
                        `title`="total", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="iqrscores",
                title="IQR scores",
                visible=TRUE,
                rows=0,
                columns=list(
                    list(
                        `name`="type", 
                        `title`="Type", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="rownum", 
                        `title`="Row number", 
                        `type`="number"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"),
                    list(
                        `name`="iqr_distance", 
                        `title`="IQR distance", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="boxplot",
                title="Boxplot",
                visible="(box)",
                width=400,
                height=300,
                renderFun=".plotBoxplot"))}))

boxplotmethodBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "boxplotmethodBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "outlierz",
                name = "boxplotmethod",
                version = c(1,0,0),
                options = options,
                results = boxplotmethodResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Boxplots
#'
#' 
#' @param data .
#' @param dep .
#' @param iqrLimitMild a number specifying iqr distance for mild outliers
#' @param iqrLimitExtreme a number specifying iqr distance for extreme
#'   outliers
#' @param box \code{TRUE} or \code{FALSE} (default), provide box plots
#'   (continuous variables only)
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$summary} \tab \tab \tab \tab \tab summary table of outlier results \cr
#'   \code{results$iqrscores} \tab \tab \tab \tab \tab a table of the outliers based on IQR scores \cr
#'   \code{results$boxplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary$asDF}
#'
#' \code{as.data.frame(results$summary)}
#'
#' @export
boxplotmethod <- function(
    data,
    dep,
    iqrLimitMild = 1.5,
    iqrLimitExtreme = 3,
    box = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("boxplotmethod requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL))


    options <- boxplotmethodOptions$new(
        dep = dep,
        iqrLimitMild = iqrLimitMild,
        iqrLimitExtreme = iqrLimitExtreme,
        box = box)

    analysis <- boxplotmethodClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

