
# This file is automatically generated, you probably don't want to edit this

outliersOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "outliersOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            useZ = TRUE,
            zLimit = 3.29,
            hist = FALSE, ...) {

            super$initialize(
                package="outlierz",
                name="outliers",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..useZ <- jmvcore::OptionBool$new(
                "useZ",
                useZ,
                default=TRUE)
            private$..zLimit <- jmvcore::OptionNumber$new(
                "zLimit",
                zLimit,
                min=0,
                default=3.29)
            private$..hist <- jmvcore::OptionBool$new(
                "hist",
                hist,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..useZ)
            self$.addOption(private$..zLimit)
            self$.addOption(private$..hist)
        }),
    active = list(
        dep = function() private$..dep$value,
        useZ = function() private$..useZ$value,
        zLimit = function() private$..zLimit$value,
        hist = function() private$..hist$value),
    private = list(
        ..dep = NA,
        ..useZ = NA,
        ..zLimit = NA,
        ..hist = NA)
)

outliersResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "outliersResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        outofrange = function() private$.items[["outofrange"]],
        zscores = function() private$.items[["zscores"]],
        hist = function() private$.items[["hist"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Outliers via Z-Scores")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Outliers"))
            self$add(jmvcore::Table$new(
                options=options,
                name="outofrange",
                title="Out of Range",
                visible="(useMin | useMax)",
                rows=0,
                columns=list(
                    list(
                        `name`="id", 
                        `title`="id", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="value", 
                        `type`="number"),
                    list(
                        `name`="outlier", 
                        `title`="outlier", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="zscores",
                title="Z Scores",
                visible="(useZ)",
                rows=0,
                columns=list(
                    list(
                        `name`="id", 
                        `title`="id", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="value", 
                        `type`="number"),
                    list(
                        `name`="zvalue", 
                        `title`="zvalue", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="hist",
                title="Histogram",
                visible="(hist)",
                width=400,
                height=300,
                renderFun=".plotHistogram"))}))

outliersBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "outliersBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "outlierz",
                name = "outliers",
                version = c(1,0,0),
                options = options,
                results = outliersResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Z-Scores
#'
#' 
#' @param data .
#' @param dep .
#' @param useZ \code{TRUE} or \code{FALSE} (default), use z-scores for outlier
#'   detection
#' @param zLimit a number specifying the min absolute z value to be considered
#'   an outlier
#' @param hist \code{TRUE} or \code{FALSE} (default), provide histograms
#'   (continuous variables only)
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$outofrange} \tab \tab \tab \tab \tab a table of the out of range values \cr
#'   \code{results$zscores} \tab \tab \tab \tab \tab a table of the outliers based on z-scores \cr
#'   \code{results$hist} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$outofrange$asDF}
#'
#' \code{as.data.frame(results$outofrange)}
#'
#' @export
outliers <- function(
    data,
    dep,
    useZ = TRUE,
    zLimit = 3.29,
    hist = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("outliers requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL))


    options <- outliersOptions$new(
        dep = dep,
        useZ = useZ,
        zLimit = zLimit,
        hist = hist)

    analysis <- outliersClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

